export const FULL_NAME_REGISTER_CHANGED = "FULL_NAME_REGISTER_CHANGED";
export const MOBILE_NUMBER_REGISTER_CHANGED = "MOBILE_NUMBER_REGISTER_CHANGED";
export const PASSWORD_REGISTER_CHANGED = "PASSWORD_REGISTER_CHANGED";
export const REPEAT_PASSWORD_CHANGED = "REPEAT_PASSWORD_CHANGED";

export const USER_NAME_CHANGED = "USER_NAME_CHANGED";
export const USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED";

export const SET_LOADING_MESSAGE = "SET_LOADING_MESSAGE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";

export const SHOW_ALERT_POP_UP = "SHOW_ALERT_POP_UP";
export const HIDE_ALERT_POP_UP = "HIDE_ALERT_POP_UP";

export const SET_LOGGED_IN_TRUE = "SET_LOGGED_IN_TRUE";
export const LOG_USER_OUT = "LOG_USER_OUT";

export const SET_NEW_USERS = "SET_NEW_USERS";
